import { jsPDF } from 'jspdf'

/**
 * Frontend-only PDF export of analysis results.
 * Future: server-side templated reports with firm branding.
 */

function riskColor(risk) {
  if (risk === 'High') return [220, 38, 38]
  if (risk === 'Medium') return [202, 138, 4]
  return [22, 163, 74]
}

export function downloadAnalysisPdf(report, firmLabel = 'ADV Guardian AI') {
  const doc = new jsPDF({ unit: 'pt', format: 'letter' })
  const margin = 48
  let y = margin
  const pageWidth = doc.internal.pageSize.getWidth()
  const contentWidth = pageWidth - margin * 2

  const line = (text, size = 11, style = 'normal', color = [30, 41, 59]) => {
    doc.setFont('helvetica', style)
    doc.setFontSize(size)
    doc.setTextColor(...color)
    const lines = doc.splitTextToSize(text, contentWidth)
    lines.forEach((ln) => {
      if (y > doc.internal.pageSize.getHeight() - margin) {
        doc.addPage()
        y = margin
      }
      doc.text(ln, margin, y)
      y += size * 1.35
    })
  }

  line(firmLabel, 18, 'bold', [31, 67, 148])
  line('Form ADV Compliance Analysis — Mock Mode Report', 12, 'normal', [71, 85, 105])
  y += 8
  line(`Generated: ${new Date(report.generatedAt).toLocaleString()}`, 10)
  if (report.summary) {
    line(
      `Overall Risk: ${report.summary.overallRisk} | Anomalies: ${report.summary.totalAnomalies}`,
      11,
      'bold'
    )
  }
  y += 12

  if (!report.anomalies?.length) {
    line(report.message || 'No anomalies identified.', 11)
  } else {
    report.anomalies.forEach((a, idx) => {
      if (y > doc.internal.pageSize.getHeight() - margin - 80) {
        doc.addPage()
        y = margin
      }
      line(`${idx + 1}. ${a.title}`, 12, 'bold', riskColor(a.riskLevel))
      line(`Risk Level: ${a.riskLevel}`, 10, 'bold', riskColor(a.riskLevel))
      line(`Explanation: ${a.explanation}`, 10)
      line(`Suggested Amendment: ${a.suggestedFix}`, 10, 'italic')
      y += 10
    })
  }

  y += 8
  line(
    'Disclaimer: This report was generated by mock heuristic analysis for demonstration purposes only. It does not constitute legal advice. Consult qualified compliance counsel before filing amendments.',
    8,
    'italic',
    [100, 116, 139]
  )

  doc.save(`adv-guardian-report-${Date.now()}.pdf`)
}
